name: API Tests

on: [ push, pull_request ]

jobs:
  up-and-running:
    runs-on: ubuntu-latest
    steps:
      - name: Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install the pipenv
        run: pip install pipenv --user
      - name: Setup Python virtual environment and install dependencies
        run: |
          PATH=$PATH:/home/ShirokamiRyzen/.local/bin
          pipenv install
      - name: Setup Python virtual environment and install development dependencies
        run: |
          PATH=$PATH:/home/ShirokamiRyzen/.local/bin
          pipenv install --dev
      - name: Run tests
        run: |
          pipenv run pytest -s
